version: "3.7"

services:
  main:
    container_name: "main"
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - 8000:8000
      - 9229:9229
    env_file:
      - .env
    command: "start:dev"

networks:
  default:
    external:
      name: mongo_default
